// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "@hey-api/client-axios";
import type {
  ListCategoriesData,
  ListCategoriesResponse,
  ListCategoriesError,
  ListDocsData,
  ListDocsResponse,
  ListDocsError,
  CreateDocData,
  CreateDocResponse,
  CreateDocError,
  DeleteDocData,
  DeleteDocResponse,
  DeleteDocError,
  GetDocData,
  GetDocResponse,
  GetDocError,
  UpdateDocData,
  UpdateDocResponse,
  UpdateDocError,
  GetSharingMetadataData,
  GetSharingMetadataResponse,
  GetSharingMetadataError,
  GetPermissionsData,
  GetPermissionsResponse,
  GetPermissionsError,
  AddPermissionData,
  AddPermissionResponse,
  AddPermissionError,
  DeletePermissionData,
  DeletePermissionResponse,
  DeletePermissionError,
  SearchPrincipalsData,
  SearchPrincipalsResponse2,
  SearchPrincipalsError,
  GetAclSettingsData,
  GetAclSettingsResponse,
  GetAclSettingsError,
  UpdateAclSettingsData,
  UpdateAclSettingsResponse,
  UpdateAclSettingsError,
  UnpublishDocData,
  UnpublishDocResponse,
  UnpublishDocError,
  PublishDocData,
  PublishDocResponse,
  PublishDocError,
  ListPagesData,
  ListPagesResponse,
  ListPagesError,
  CreatePageData,
  CreatePageResponse,
  CreatePageError,
  DeletePageData,
  DeletePageResponse,
  DeletePageError,
  GetPageData,
  GetPageResponse,
  GetPageError,
  UpdatePageData,
  UpdatePageResponse,
  UpdatePageError,
  BeginPageContentExportData,
  BeginPageContentExportResponse2,
  BeginPageContentExportError,
  GetPageContentExportStatusData,
  GetPageContentExportStatusResponse,
  GetPageContentExportStatusError,
  ListTablesData,
  ListTablesResponse,
  ListTablesError,
  GetTableData,
  GetTableResponse,
  GetTableError,
  ListColumnsData,
  ListColumnsResponse,
  ListColumnsError,
  DeleteRowsData,
  DeleteRowsResponse,
  DeleteRowsError,
  ListRowsData,
  ListRowsResponse,
  ListRowsError,
  UpsertRowsData,
  UpsertRowsResponse,
  UpsertRowsError,
  DeleteRowData,
  DeleteRowResponse,
  DeleteRowError,
  GetRowData,
  GetRowResponse,
  GetRowError,
  UpdateRowData,
  UpdateRowResponse,
  UpdateRowError,
  PushButtonData,
  PushButtonResponse,
  PushButtonError,
  GetColumnData,
  GetColumnResponse,
  GetColumnError,
  ListFormulasData,
  ListFormulasResponse,
  ListFormulasError,
  GetFormulaData,
  GetFormulaResponse,
  GetFormulaError,
  ListControlsData,
  ListControlsResponse,
  ListControlsError,
  GetControlData,
  GetControlResponse,
  GetControlError,
  ListCustomDocDomainsData,
  ListCustomDocDomainsResponse,
  ListCustomDocDomainsError,
  AddCustomDocDomainData,
  AddCustomDocDomainResponse2,
  AddCustomDocDomainError,
  DeleteCustomDocDomainData,
  DeleteCustomDocDomainResponse2,
  DeleteCustomDocDomainError,
  UpdateCustomDocDomainData,
  UpdateCustomDocDomainResponse2,
  UpdateCustomDocDomainError,
  GetCustomDocDomainProviderData,
  GetCustomDocDomainProviderResponse,
  GetCustomDocDomainProviderError,
  WhoamiData,
  WhoamiResponse,
  WhoamiError,
  ResolveBrowserLinkData,
  ResolveBrowserLinkResponse,
  ResolveBrowserLinkError,
  GetMutationStatusData,
  GetMutationStatusResponse,
  GetMutationStatusError,
  TriggerWebhookAutomationData,
  TriggerWebhookAutomationResponse,
  TriggerWebhookAutomationError,
  ListDocAnalyticsData,
  ListDocAnalyticsResponse,
  ListDocAnalyticsError,
  ListPageAnalyticsData,
  ListPageAnalyticsResponse,
  ListPageAnalyticsError,
  ListDocAnalyticsSummaryData,
  ListDocAnalyticsSummaryResponse,
  ListDocAnalyticsSummaryError,
  ListPackAnalyticsData,
  ListPackAnalyticsResponse,
  ListPackAnalyticsError,
  ListPackAnalyticsSummaryData,
  ListPackAnalyticsSummaryResponse,
  ListPackAnalyticsSummaryError,
  ListPackFormulaAnalyticsData,
  ListPackFormulaAnalyticsResponse,
  ListPackFormulaAnalyticsError,
  GetAnalyticsLastUpdatedData,
  GetAnalyticsLastUpdatedResponse,
  GetAnalyticsLastUpdatedError,
  ListWorkspaceMembersData,
  ListWorkspaceMembersResponse,
  ListWorkspaceMembersError,
  ChangeUserRoleData,
  ChangeUserRoleResponse,
  ChangeUserRoleError,
  ListWorkspaceRoleActivityData,
  ListWorkspaceRoleActivityResponse,
  ListWorkspaceRoleActivityError,
  ListPacksData,
  ListPacksResponse,
  ListPacksError,
  CreatePackData,
  CreatePackResponse2,
  CreatePackError,
  DeletePackData,
  DeletePackResponse2,
  DeletePackError,
  GetPackData,
  GetPackResponse,
  GetPackError,
  UpdatePackData,
  UpdatePackResponse,
  UpdatePackError,
  GetPackConfigurationSchemaData,
  GetPackConfigurationSchemaResponse,
  GetPackConfigurationSchemaError,
  ListPackVersionsData,
  ListPackVersionsResponse,
  ListPackVersionsError,
  GetNextPackVersionData,
  GetNextPackVersionResponse,
  GetNextPackVersionError,
  GetPackVersionDiffsData,
  GetPackVersionDiffsResponse,
  GetPackVersionDiffsError,
  RegisterPackVersionData,
  RegisterPackVersionResponse,
  RegisterPackVersionError,
  PackVersionUploadCompleteData,
  PackVersionUploadCompleteResponse,
  PackVersionUploadCompleteError,
  ListPackReleasesData,
  ListPackReleasesResponse,
  ListPackReleasesError,
  CreatePackReleaseData,
  CreatePackReleaseResponse,
  CreatePackReleaseError,
  UpdatePackReleaseData,
  UpdatePackReleaseResponse,
  UpdatePackReleaseError,
  GetPackOauthConfigData,
  GetPackOauthConfigResponse,
  GetPackOauthConfigError,
  SetPackOauthConfigData,
  SetPackOauthConfigResponse,
  SetPackOauthConfigError,
  GetPackSystemConnectionData,
  GetPackSystemConnectionResponse,
  GetPackSystemConnectionError,
  PatchPackSystemConnectionData,
  PatchPackSystemConnectionResponse,
  PatchPackSystemConnectionError,
  SetPackSystemConnectionData,
  SetPackSystemConnectionResponse,
  SetPackSystemConnectionError,
  GetPackPermissionsData,
  GetPackPermissionsResponse,
  GetPackPermissionsError,
  AddPackPermissionData,
  AddPackPermissionResponse2,
  AddPackPermissionError,
  DeletePackPermissionData,
  DeletePackPermissionResponse2,
  DeletePackPermissionError,
  ListPackMakersData,
  ListPackMakersResponse2,
  ListPackMakersError,
  AddPackMakerData,
  AddPackMakerResponse2,
  AddPackMakerError,
  DeletePackMakerData,
  DeletePackMakerResponse2,
  DeletePackMakerError,
  ListPackCategoriesData,
  ListPackCategoriesResponse2,
  ListPackCategoriesError,
  AddPackCategoryData,
  AddPackCategoryResponse2,
  AddPackCategoryError,
  DeletePackCategoryData,
  DeletePackCategoryResponse2,
  DeletePackCategoryError,
  UploadPackAssetData,
  UploadPackAssetResponse,
  UploadPackAssetError,
  UploadPackSourceCodeData,
  UploadPackSourceCodeResponse,
  UploadPackSourceCodeError,
  PackAssetUploadCompleteData,
  PackAssetUploadCompleteResponse2,
  PackAssetUploadCompleteError,
  PackSourceCodeUploadCompleteData,
  PackSourceCodeUploadCompleteResponse2,
  PackSourceCodeUploadCompleteError,
  GetPackSourceCodeData,
  GetPackSourceCodeResponse,
  GetPackSourceCodeError,
  ListPackListingsData,
  ListPackListingsResponse,
  ListPackListingsError,
  GetPackListingData,
  GetPackListingResponse,
  GetPackListingError,
  ListPackLogsData,
  ListPackLogsResponse,
  ListPackLogsError,
  ListIngestionLogsData,
  ListIngestionLogsResponse,
  ListIngestionLogsError,
  ListGroupedPackLogsData,
  ListGroupedPackLogsResponse,
  ListGroupedPackLogsError,
  ListGroupedIngestionLogsData,
  ListGroupedIngestionLogsResponse,
  ListGroupedIngestionLogsError,
  ListIngestionExecutionsData,
  ListIngestionExecutionsResponse,
  ListIngestionExecutionsError,
  ListIngestionExecutionAttemptsData,
  ListIngestionExecutionAttemptsResponse,
  ListIngestionExecutionAttemptsError,
  GetPackLogDetailsData,
  GetPackLogDetailsResponse,
  GetPackLogDetailsError,
  ListPackFeaturedDocsData,
  ListPackFeaturedDocsResponse,
  ListPackFeaturedDocsError,
  UpdatePackFeaturedDocsData,
  UpdatePackFeaturedDocsResponse2,
  UpdatePackFeaturedDocsError,
  AddGoLinkData,
  AddGoLinkResponse,
  AddGoLinkError,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get doc categories
 * Gets all available doc categories.
 */
export const listCategories = <ThrowOnError extends boolean = false>(
  options?: Options<ListCategoriesData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<ListCategoriesResponse, ListCategoriesError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/categories",
    ...options,
  });
};

/**
 * List available docs
 * Returns a list of Coda docs accessible by the user, and which they have opened at least once. These are returned in the same order as on the docs page: reverse chronological by the latest event relevant to the user (last viewed, edited, or shared).
 *
 */
export const listDocs = <ThrowOnError extends boolean = false>(options?: Options<ListDocsData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<ListDocsResponse, ListDocsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs",
    ...options,
  });
};

/**
 * Create doc
 * Creates a new Coda doc, optionally copying an existing doc. Note that creating a doc requires you to be a Doc Maker in the applicable workspace (or be auto-promoted to one).
 *
 */
export const createDoc = <ThrowOnError extends boolean = false>(options: Options<CreateDocData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<CreateDocResponse, CreateDocError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete doc
 * Deletes a doc.
 */
export const deleteDoc = <ThrowOnError extends boolean = false>(options: Options<DeleteDocData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).delete<DeleteDocResponse, DeleteDocError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}",
    ...options,
  });
};

/**
 * Get info about a doc
 * Returns metadata for the specified doc.
 */
export const getDoc = <ThrowOnError extends boolean = false>(options: Options<GetDocData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetDocResponse, GetDocError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}",
    ...options,
  });
};

/**
 * Update doc
 * Updates metadata for a doc. Note that updating a doc title requires you to be a Doc Maker in the applicable workspace.
 */
export const updateDoc = <ThrowOnError extends boolean = false>(options: Options<UpdateDocData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).patch<UpdateDocResponse, UpdateDocError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Get sharing metadata
 * Returns metadata associated with sharing for this Coda doc.
 */
export const getSharingMetadata = <ThrowOnError extends boolean = false>(
  options: Options<GetSharingMetadataData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetSharingMetadataResponse, GetSharingMetadataError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/acl/metadata",
    ...options,
  });
};

/**
 * List permissions
 * Returns a list of permissions for this Coda doc.
 */
export const getPermissions = <ThrowOnError extends boolean = false>(
  options: Options<GetPermissionsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetPermissionsResponse, GetPermissionsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/acl/permissions",
    ...options,
  });
};

/**
 * Add permission
 * Adds a new permission to the doc.
 *
 */
export const addPermission = <ThrowOnError extends boolean = false>(
  options: Options<AddPermissionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<AddPermissionResponse, AddPermissionError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/acl/permissions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete permission
 * Deletes an existing permission.
 *
 */
export const deletePermission = <ThrowOnError extends boolean = false>(
  options: Options<DeletePermissionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<DeletePermissionResponse, DeletePermissionError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/acl/permissions/{permissionId}",
    ...options,
  });
};

/**
 * Search principals
 * Searches for user and group principals matching the query that this doc can be shared with.
 * At most 20 results will be returned for both users and groups. If no query is given then no results are returned.
 *
 */
export const searchPrincipals = <ThrowOnError extends boolean = false>(
  options: Options<SearchPrincipalsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<SearchPrincipalsResponse2, SearchPrincipalsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/acl/principals/search",
    ...options,
  });
};

/**
 * Get ACL settings
 * Returns settings associated with ACLs for this Coda doc.
 */
export const getAclSettings = <ThrowOnError extends boolean = false>(
  options: Options<GetAclSettingsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetAclSettingsResponse, GetAclSettingsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/acl/settings",
    ...options,
  });
};

/**
 * Update ACL settings
 * Update settings associated with ACLs for this Coda doc.
 */
export const updateAclSettings = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAclSettingsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<UpdateAclSettingsResponse, UpdateAclSettingsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/acl/settings",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Unpublish doc
 * Unpublishes a doc.
 */
export const unpublishDoc = <ThrowOnError extends boolean = false>(
  options: Options<UnpublishDocData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<UnpublishDocResponse, UnpublishDocError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/publish",
    ...options,
  });
};

/**
 * Publish doc
 * Update publish settings for a doc.
 */
export const publishDoc = <ThrowOnError extends boolean = false>(options: Options<PublishDocData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).put<PublishDocResponse, PublishDocError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/publish",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * List pages
 * Returns a list of pages in a Coda doc.
 */
export const listPages = <ThrowOnError extends boolean = false>(options: Options<ListPagesData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<ListPagesResponse, ListPagesError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/pages",
    ...options,
  });
};

/**
 * Create a page
 * Create a new page in a doc. Note that creating a page requires you to be a Doc Maker in the applicable workspace.
 *
 */
export const createPage = <ThrowOnError extends boolean = false>(options: Options<CreatePageData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<CreatePageResponse, CreatePageError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/pages",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete a page
 * Deletes the specified page.
 */
export const deletePage = <ThrowOnError extends boolean = false>(options: Options<DeletePageData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).delete<DeletePageResponse, DeletePageError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/pages/{pageIdOrName}",
    ...options,
  });
};

/**
 * Get a page
 * Returns details about a page.
 */
export const getPage = <ThrowOnError extends boolean = false>(options: Options<GetPageData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetPageResponse, GetPageError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/pages/{pageIdOrName}",
    ...options,
  });
};

/**
 * Update a page
 * Update properties for a page. Note that updating a page title or icon requires you to be a Doc Maker in the applicable workspace.
 *
 */
export const updatePage = <ThrowOnError extends boolean = false>(options: Options<UpdatePageData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).put<UpdatePageResponse, UpdatePageError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/pages/{pageIdOrName}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Begin content export
 * Initiate an export of content for the given page.
 */
export const beginPageContentExport = <ThrowOnError extends boolean = false>(
  options: Options<BeginPageContentExportData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    BeginPageContentExportResponse2,
    BeginPageContentExportError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/pages/{pageIdOrName}/export",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Content export status
 * Check the status of a page content export
 */
export const getPageContentExportStatus = <ThrowOnError extends boolean = false>(
  options: Options<GetPageContentExportStatusData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetPageContentExportStatusResponse,
    GetPageContentExportStatusError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/pages/{pageIdOrName}/export/{requestId}",
    ...options,
  });
};

/**
 * List tables
 * Returns a list of tables in a Coda doc.
 */
export const listTables = <ThrowOnError extends boolean = false>(options: Options<ListTablesData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<ListTablesResponse, ListTablesError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    querySerializer: {
      array: {
        explode: false,
        style: "form",
      },
    },
    url: "/docs/{docId}/tables",
    ...options,
  });
};

/**
 * Get a table
 * Returns details about a specific table or view.
 */
export const getTable = <ThrowOnError extends boolean = false>(options: Options<GetTableData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetTableResponse, GetTableError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/tables/{tableIdOrName}",
    ...options,
  });
};

/**
 * List columns
 * Returns a list of columns in a table.
 */
export const listColumns = <ThrowOnError extends boolean = false>(options: Options<ListColumnsData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<ListColumnsResponse, ListColumnsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/tables/{tableIdOrName}/columns",
    ...options,
  });
};

/**
 * Delete multiple rows
 * Deletes the specified rows from the table or view. This endpoint will always return a 202. Row deletions are generally processed within several seconds.
 *
 */
export const deleteRows = <ThrowOnError extends boolean = false>(options: Options<DeleteRowsData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).delete<DeleteRowsResponse, DeleteRowsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/tables/{tableIdOrName}/rows",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * List table rows
 * Returns a list of rows in a table.
 * ### Value results
 * The `valueFormat` parameter dictates in what format the API should return values for individual cells.
 * * `simple` (default): Returns cell values as the following JSON values: `string`, `number`, or `boolean`. Array values (like multiselects) are returned as comma-delimited strings.
 * * `simpleWithArrays`: Singleton values are returned as `simple`. Array values are returned as JSON arrays and the values within are `simple` values (including nested arrays).
 * * `rich`: If applicable, returns many values with further encoding, allowing API users to have lossless access to data in Coda.
 * * For `text` values, returns data in Markdown syntax. If the text field is simple text (e.g. has no formatting),
 * the field will be fully escaped with triple-ticks. E.g
 * `
 * ```This is plain text```
 * `
 * * For `currency`, `lookup`, `image`, `person` and `hyperlink` values, the value will be encoded in [JSON-LD](https://json-ld.org/) format.
 *
 * ```
 * // Currency
 * {
 * "@context": "http://schema.org",
 * "@type": "MonetaryAmount",
 * "currency": "USD",
 * "amount": 42.42
 * }
 *
 * // Lookup
 * {
 * "@context": "http://schema.org",
 * "@type": "StructuredValue",
 * "additionalType": "row",
 * "name": "Row Name",
 * "rowId": "i-123456789",
 * "tableId": "grid-123456789",
 * "tableUrl": "https://coda.io/d/_d123456789/grid-123456789",
 * "url": "https://coda.io/d/_d123456789/grid-123456789#_r42",
 * }
 *
 * // Hyperlink
 * {
 * "@context": "http://schema.org",
 * "@type": "WebPage",
 * "name": "Coda",
 * "url": "https://coda.io"
 * }
 *
 * // Image
 * {
 * "@context": "http://schema.org",
 * "@type": "ImageObject",
 * "name": "Coda logo",
 * "url": "https://coda.io/logo.jpg"
 * }
 *
 * // People
 * {
 * "@context": "http://schema.org",
 * "@type": "Person",
 * "name": "Art Vandalay",
 * "email": "art@vandalayindustries.com"
 * }
 * ```
 *
 */
export const listRows = <ThrowOnError extends boolean = false>(options: Options<ListRowsData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<ListRowsResponse, ListRowsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/tables/{tableIdOrName}/rows",
    ...options,
  });
};

/**
 * Insert/upsert rows
 * Inserts rows into a table, optionally updating existing rows if any upsert key columns are provided. This endpoint will always return a 202, so long as the doc and table exist and are accessible (and the update is structurally valid). Row inserts/upserts are generally processed within several seconds. Note: this endpoint only works for base tables, not views.
 * When upserting, if multiple rows match the specified key column(s), they will all be updated with the specified value.
 *
 */
export const upsertRows = <ThrowOnError extends boolean = false>(options: Options<UpsertRowsData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<UpsertRowsResponse, UpsertRowsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/tables/{tableIdOrName}/rows",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete row
 * Deletes the specified row from the table or view. This endpoint will always return a 202, so long as the row exists and is accessible (and the update is structurally valid). Row deletions are generally processed within several seconds. When deleting using a name as opposed to an ID, an arbitrary row will be removed.
 *
 */
export const deleteRow = <ThrowOnError extends boolean = false>(options: Options<DeleteRowData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).delete<DeleteRowResponse, DeleteRowError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/tables/{tableIdOrName}/rows/{rowIdOrName}",
    ...options,
  });
};

/**
 * Get a row
 * Returns details about a row in a table.
 */
export const getRow = <ThrowOnError extends boolean = false>(options: Options<GetRowData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetRowResponse, GetRowError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/tables/{tableIdOrName}/rows/{rowIdOrName}",
    ...options,
  });
};

/**
 * Update row
 * Updates the specified row in the table. This endpoint will always return a 202, so long as the row exists and is accessible (and the update is structurally valid). Row updates are generally processed within several seconds. When updating using a name as opposed to an ID, an arbitrary row will be affected.
 *
 */
export const updateRow = <ThrowOnError extends boolean = false>(options: Options<UpdateRowData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).put<UpdateRowResponse, UpdateRowError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/tables/{tableIdOrName}/rows/{rowIdOrName}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Push a button
 * Pushes a button on a row in a table.
 * Authorization note: This action is available to API tokens that are authorized to write to the table. However, the underlying button can perform any action on the document, including writing to other tables and performing Pack actions.
 *
 */
export const pushButton = <ThrowOnError extends boolean = false>(options: Options<PushButtonData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<PushButtonResponse, PushButtonError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/tables/{tableIdOrName}/rows/{rowIdOrName}/buttons/{columnIdOrName}",
    ...options,
  });
};

/**
 * Get a column
 * Returns details about a column in a table.
 */
export const getColumn = <ThrowOnError extends boolean = false>(options: Options<GetColumnData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetColumnResponse, GetColumnError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/tables/{tableIdOrName}/columns/{columnIdOrName}",
    ...options,
  });
};

/**
 * List formulas
 * Returns a list of named formulas in a Coda doc.
 */
export const listFormulas = <ThrowOnError extends boolean = false>(
  options: Options<ListFormulasData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<ListFormulasResponse, ListFormulasError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/formulas",
    ...options,
  });
};

/**
 * Get a formula
 * Returns info on a formula.
 */
export const getFormula = <ThrowOnError extends boolean = false>(options: Options<GetFormulaData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetFormulaResponse, GetFormulaError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/formulas/{formulaIdOrName}",
    ...options,
  });
};

/**
 * List controls
 * Returns a list of controls in a Coda doc.
 */
export const listControls = <ThrowOnError extends boolean = false>(
  options: Options<ListControlsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<ListControlsResponse, ListControlsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/controls",
    ...options,
  });
};

/**
 * Get a control
 * Returns info on a control.
 */
export const getControl = <ThrowOnError extends boolean = false>(options: Options<GetControlData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetControlResponse, GetControlError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/controls/{controlIdOrName}",
    ...options,
  });
};

/**
 * List custom doc domains
 * List all custom domains for a published doc.
 */
export const listCustomDocDomains = <ThrowOnError extends boolean = false>(
  options: Options<ListCustomDocDomainsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<ListCustomDocDomainsResponse, ListCustomDocDomainsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/${docId}/domains",
    ...options,
  });
};

/**
 * Add custom domain
 * Add a custom domain to a published doc.
 */
export const addCustomDocDomain = <ThrowOnError extends boolean = false>(
  options: Options<AddCustomDocDomainData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<AddCustomDocDomainResponse2, AddCustomDocDomainError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/${docId}/domains",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Deletes a custom domain
 * Deletes a custom domain from a published doc.
 */
export const deleteCustomDocDomain = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCustomDocDomainData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteCustomDocDomainResponse2,
    DeleteCustomDocDomainError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/domains/{customDocDomain}",
    ...options,
  });
};

/**
 * Updates a custom domain
 * Updates properties of a document's custom domain.
 */
export const updateCustomDocDomain = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCustomDocDomainData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateCustomDocDomainResponse2,
    UpdateCustomDocDomainError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/domains/{customDocDomain}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Gets custom doc domains providers
 * Gets the provider (ie. GoDaddy) of a custom domain.
 */
export const getCustomDocDomainProvider = <ThrowOnError extends boolean = false>(
  options: Options<GetCustomDocDomainProviderData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetCustomDocDomainProviderResponse,
    GetCustomDocDomainProviderError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/domains/provider/{customDocDomain}",
    ...options,
  });
};

/**
 * Get user info
 * Returns basic info about the current user.
 */
export const whoami = <ThrowOnError extends boolean = false>(options?: Options<WhoamiData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<WhoamiResponse, WhoamiError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/whoami",
    ...options,
  });
};

/**
 * Resolve browser link
 * Given a browser link to a Coda object, attempts to find it and return metadata that can be used to get more info on it. Returns a 400 if the URL does not appear to be a Coda URL or a 404 if the resource cannot be located with the current credentials.
 *
 */
export const resolveBrowserLink = <ThrowOnError extends boolean = false>(
  options: Options<ResolveBrowserLinkData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<ResolveBrowserLinkResponse, ResolveBrowserLinkError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/resolveBrowserLink",
    ...options,
  });
};

/**
 * Get mutation status
 * Get the status for an asynchronous mutation to know whether or not it has been completed. Each API endpoint that mutates a document will return a request id that you can pass to this endpoint to check the completion status. Status information is not guaranteed to be available for more than one day after the mutation was completed. It is intended to be used shortly after the request was made.
 *
 */
export const getMutationStatus = <ThrowOnError extends boolean = false>(
  options: Options<GetMutationStatusData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetMutationStatusResponse, GetMutationStatusError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/mutationStatus/{requestId}",
    ...options,
  });
};

/**
 * Trigger automation
 * Triggers webhook-invoked automation
 */
export const triggerWebhookAutomation = <ThrowOnError extends boolean = false>(
  options: Options<TriggerWebhookAutomationData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    TriggerWebhookAutomationResponse,
    TriggerWebhookAutomationError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{docId}/hooks/automation/{ruleId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * List doc analytics
 * Returns analytics data for available docs per day.
 *
 */
export const listDocAnalytics = <ThrowOnError extends boolean = false>(
  options?: Options<ListDocAnalyticsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<ListDocAnalyticsResponse, ListDocAnalyticsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    querySerializer: {
      array: {
        explode: false,
        style: "form",
      },
    },
    url: "/analytics/docs",
    ...options,
  });
};

/**
 * List page analytics
 * Returns analytics data for a given doc within the day.
 * This method will return a 401 if the given doc is not in an Enterprise workspace.
 *
 */
export const listPageAnalytics = <ThrowOnError extends boolean = false>(
  options: Options<ListPageAnalyticsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<ListPageAnalyticsResponse, ListPageAnalyticsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/analytics/docs/{docId}/pages",
    ...options,
  });
};

/**
 * Get doc analytics summary
 * Returns summarized analytics data for available docs.
 *
 */
export const listDocAnalyticsSummary = <ThrowOnError extends boolean = false>(
  options?: Options<ListDocAnalyticsSummaryData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListDocAnalyticsSummaryResponse,
    ListDocAnalyticsSummaryError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/analytics/docs/summary",
    ...options,
  });
};

/**
 * List Pack analytics
 * Returns analytics data for Packs the user can edit.
 *
 */
export const listPackAnalytics = <ThrowOnError extends boolean = false>(
  options?: Options<ListPackAnalyticsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<ListPackAnalyticsResponse, ListPackAnalyticsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    querySerializer: {
      array: {
        explode: false,
        style: "form",
      },
    },
    url: "/analytics/packs",
    ...options,
  });
};

/**
 * Get Pack analytics summary
 * Returns summarized analytics data for Packs the user can edit.
 *
 */
export const listPackAnalyticsSummary = <ThrowOnError extends boolean = false>(
  options?: Options<ListPackAnalyticsSummaryData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListPackAnalyticsSummaryResponse,
    ListPackAnalyticsSummaryError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    querySerializer: {
      array: {
        explode: false,
        style: "form",
      },
    },
    url: "/analytics/packs/summary",
    ...options,
  });
};

/**
 * List Pack formula analytics
 * Returns analytics data for Pack formulas.
 *
 */
export const listPackFormulaAnalytics = <ThrowOnError extends boolean = false>(
  options: Options<ListPackFormulaAnalyticsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListPackFormulaAnalyticsResponse,
    ListPackFormulaAnalyticsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    querySerializer: {
      array: {
        explode: false,
        style: "form",
      },
    },
    url: "/analytics/packs/{packId}/formulas",
    ...options,
  });
};

/**
 * Get analytics last updated day
 * Returns days based on Pacific Standard Time when analytics were last updated.
 *
 */
export const getAnalyticsLastUpdated = <ThrowOnError extends boolean = false>(
  options?: Options<GetAnalyticsLastUpdatedData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetAnalyticsLastUpdatedResponse,
    GetAnalyticsLastUpdatedError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/analytics/updated",
    ...options,
  });
};

/**
 * List workspace users
 * Returns a list of members in the given workspace. This list will be ordered with the requesting user first and then ordered by role.
 *
 */
export const listWorkspaceMembers = <ThrowOnError extends boolean = false>(
  options: Options<ListWorkspaceMembersData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<ListWorkspaceMembersResponse, ListWorkspaceMembersError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    querySerializer: {
      array: {
        explode: false,
        style: "form",
      },
    },
    url: "/workspaces/{workspaceId}/users",
    ...options,
  });
};

/**
 * Updates user role
 * Updates the workspace user role of a user that matches the parameters. Only succeeds if the requesting user has admin permissions in the workspace.
 *
 */
export const changeUserRole = <ThrowOnError extends boolean = false>(
  options: Options<ChangeUserRoleData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<ChangeUserRoleResponse, ChangeUserRoleError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/workspaces/{workspaceId}/users/role",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * List workspace roles
 * Returns a list of the counts of users over time by role for the workspace.
 *
 */
export const listWorkspaceRoleActivity = <ThrowOnError extends boolean = false>(
  options: Options<ListWorkspaceRoleActivityData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListWorkspaceRoleActivityResponse,
    ListWorkspaceRoleActivityError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/workspaces/{workspaceId}/roles",
    ...options,
  });
};

/**
 * List Packs
 * Get the list of accessible Packs.
 *
 */
export const listPacks = <ThrowOnError extends boolean = false>(options?: Options<ListPacksData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<ListPacksResponse, ListPacksError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    querySerializer: {
      array: {
        explode: false,
        style: "form",
      },
    },
    url: "/packs",
    ...options,
  });
};

/**
 * Create Pack
 * Creates a new Pack, essentially registering a new Pack ID. The contents of the Pack will be uploaded separately.
 *
 */
export const createPack = <ThrowOnError extends boolean = false>(options: Options<CreatePackData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<CreatePackResponse2, CreatePackError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete Pack
 * Delete a given Pack.
 *
 */
export const deletePack = <ThrowOnError extends boolean = false>(options: Options<DeletePackData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).delete<DeletePackResponse2, DeletePackError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}",
    ...options,
  });
};

/**
 * Get a single Pack
 * Returns a single Pack.
 *
 */
export const getPack = <ThrowOnError extends boolean = false>(options: Options<GetPackData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetPackResponse, GetPackError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}",
    ...options,
  });
};

/**
 * Update Pack
 * Update an existing Pack for non-versioned fields.
 *
 */
export const updatePack = <ThrowOnError extends boolean = false>(options: Options<UpdatePackData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).patch<UpdatePackResponse, UpdatePackError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Gets the JSON Schema for Pack configuration.
 * Returns a JSON Schema applicable for customizing the pack using Pack configurations.
 *
 */
export const getPackConfigurationSchema = <ThrowOnError extends boolean = false>(
  options: Options<GetPackConfigurationSchemaData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetPackConfigurationSchemaResponse,
    GetPackConfigurationSchemaError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/configurations/schema",
    ...options,
  });
};

/**
 * List the versions for a Pack.
 * Get the list of versions of a Pack.
 *
 */
export const listPackVersions = <ThrowOnError extends boolean = false>(
  options: Options<ListPackVersionsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<ListPackVersionsResponse, ListPackVersionsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/versions",
    ...options,
  });
};

/**
 * Get the next valid version for a Pack.
 * Get the next valid version based on the proposed metadata.
 *
 */
export const getNextPackVersion = <ThrowOnError extends boolean = false>(
  options: Options<GetNextPackVersionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<GetNextPackVersionResponse, GetNextPackVersionError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/nextVersion",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Get the difference between two pack versions.
 * Gets information about the difference between the specified previous version and next version of a Pack.
 *
 */
export const getPackVersionDiffs = <ThrowOnError extends boolean = false>(
  options: Options<GetPackVersionDiffsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetPackVersionDiffsResponse, GetPackVersionDiffsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/versions/{basePackVersion}/diff/{targetPackVersion}",
    ...options,
  });
};

/**
 * Register Pack version
 * Registers a new Pack version. This simply returns a signed URL to use for uploading the Pack version definition. Following the completion of the upload, POST to /apis/v1/packs/{packId}/versions/{packVersion} trigger the rest of the creation process.
 *
 */
export const registerPackVersion = <ThrowOnError extends boolean = false>(
  options: Options<RegisterPackVersionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<RegisterPackVersionResponse, RegisterPackVersionError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/versions/{packVersion}/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Pack version upload complete
 * Note the completion of the upload of a Pack version bundle in order to create that Pack version.
 *
 */
export const packVersionUploadComplete = <ThrowOnError extends boolean = false>(
  options: Options<PackVersionUploadCompleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PackVersionUploadCompleteResponse,
    PackVersionUploadCompleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/versions/{packVersion}/uploadComplete",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * List the releases for a Pack.
 * Get the list of releases of a Pack.
 *
 */
export const listPackReleases = <ThrowOnError extends boolean = false>(
  options: Options<ListPackReleasesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<ListPackReleasesResponse, ListPackReleasesError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/releases",
    ...options,
  });
};

/**
 * Create a new Pack release.
 * Creates a new Pack release based on an existing Pack version.
 *
 */
export const createPackRelease = <ThrowOnError extends boolean = false>(
  options: Options<CreatePackReleaseData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<CreatePackReleaseResponse, CreatePackReleaseError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/releases",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Update an existing Pack release.
 * Update details of a Pack release.
 *
 */
export const updatePackRelease = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePackReleaseData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<UpdatePackReleaseResponse, UpdatePackReleaseError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/releases/{packReleaseId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Retrieve the OAuth configuration of the Pack.
 * Retrieve the OAuth configuration of the Pack for display purpose. Secrets will be returned with masks.
 *
 */
export const getPackOauthConfig = <ThrowOnError extends boolean = false>(
  options: Options<GetPackOauthConfigData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetPackOauthConfigResponse, GetPackOauthConfigError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/oauthConfig",
    ...options,
  });
};

/**
 * Set the OAuth configurations of the Pack.
 * Set the OAuth configurations of the Pack, including client id and secret.
 *
 */
export const setPackOauthConfig = <ThrowOnError extends boolean = false>(
  options: Options<SetPackOauthConfigData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<SetPackOauthConfigResponse, SetPackOauthConfigError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/oauthConfig",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Retrieve the system connection metadata of the Pack.
 * Retrieve the system connection metadata of the Pack.
 *
 */
export const getPackSystemConnection = <ThrowOnError extends boolean = false>(
  options: Options<GetPackSystemConnectionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetPackSystemConnectionResponse,
    GetPackSystemConnectionError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/systemConnection",
    ...options,
  });
};

/**
 * Patch the system connection credentials of the Pack.
 * Patch the system connection credentials of the Pack.
 *
 */
export const patchPackSystemConnection = <ThrowOnError extends boolean = false>(
  options: Options<PatchPackSystemConnectionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchPackSystemConnectionResponse,
    PatchPackSystemConnectionError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/systemConnection",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Set the system connection credentials of the Pack.
 * Set the system connection credentials of the Pack.
 *
 */
export const setPackSystemConnection = <ThrowOnError extends boolean = false>(
  options: Options<SetPackSystemConnectionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    SetPackSystemConnectionResponse,
    SetPackSystemConnectionError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/systemConnection",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * List permissions for a Pack
 * Get user, workspace, and/or global permissions for a given Pack.
 *
 */
export const getPackPermissions = <ThrowOnError extends boolean = false>(
  options: Options<GetPackPermissionsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetPackPermissionsResponse, GetPackPermissionsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/permissions",
    ...options,
  });
};

/**
 * Add a permission for Pack
 * Create or modify user, workspace, or global permissions for a given Pack.
 *
 */
export const addPackPermission = <ThrowOnError extends boolean = false>(
  options: Options<AddPackPermissionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<AddPackPermissionResponse2, AddPackPermissionError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/permissions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete a permission for Pack
 * Delete user, workspace, or global permissions for a given Pack.
 *
 */
export const deletePackPermission = <ThrowOnError extends boolean = false>(
  options: Options<DeletePackPermissionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeletePackPermissionResponse2,
    DeletePackPermissionError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/permissions/{permissionId}",
    ...options,
  });
};

/**
 * List makers for Pack
 * List makers for a given pack.
 *
 */
export const listPackMakers = <ThrowOnError extends boolean = false>(
  options: Options<ListPackMakersData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<ListPackMakersResponse2, ListPackMakersError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/makers",
    ...options,
  });
};

/**
 * Add a maker for Pack
 * Set a maker for a given Pack. Used to display makers for a pack in the corresponding packs page.
 *
 */
export const addPackMaker = <ThrowOnError extends boolean = false>(
  options: Options<AddPackMakerData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<AddPackMakerResponse2, AddPackMakerError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/maker",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete a maker for Pack
 * Delete a maker for a given Pack, who will not be displayed in the corresponding packs page.
 *
 */
export const deletePackMaker = <ThrowOnError extends boolean = false>(
  options: Options<DeletePackMakerData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<DeletePackMakerResponse2, DeletePackMakerError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/maker/{loginId}",
    ...options,
  });
};

/**
 * List categories for Pack
 * List publishing categories for a given pack.
 *
 */
export const listPackCategories = <ThrowOnError extends boolean = false>(
  options: Options<ListPackCategoriesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<ListPackCategoriesResponse2, ListPackCategoriesError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/categories",
    ...options,
  });
};

/**
 * Add a category for Pack
 * Add a publishing category for a given pack.
 *
 */
export const addPackCategory = <ThrowOnError extends boolean = false>(
  options: Options<AddPackCategoryData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<AddPackCategoryResponse2, AddPackCategoryError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/category",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete a category for Pack
 * Delete a publishing category for a given pack.
 *
 */
export const deletePackCategory = <ThrowOnError extends boolean = false>(
  options: Options<DeletePackCategoryData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<DeletePackCategoryResponse2, DeletePackCategoryError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/category/{categoryName}",
    ...options,
  });
};

/**
 * Upload a Pack asset.
 * Request a signed s3 URL to upload your Pack asset.
 *
 */
export const uploadPackAsset = <ThrowOnError extends boolean = false>(
  options: Options<UploadPackAssetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<UploadPackAssetResponse, UploadPackAssetError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/uploadAsset",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Upload Pack source code.
 * Request a signed s3 URL to upload your Pack source code.
 *
 */
export const uploadPackSourceCode = <ThrowOnError extends boolean = false>(
  options: Options<UploadPackSourceCodeData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<UploadPackSourceCodeResponse, UploadPackSourceCodeError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/uploadSourceCode",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Pack asset upload complete
 * Note the completion of the upload of a Pack asset.
 *
 */
export const packAssetUploadComplete = <ThrowOnError extends boolean = false>(
  options: Options<PackAssetUploadCompleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PackAssetUploadCompleteResponse2,
    PackAssetUploadCompleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/assets/{packAssetId}/assetType/{packAssetType}/uploadComplete",
    ...options,
  });
};

/**
 * Pack source code upload complete
 * Note the completion of the upload of a Pack source code.
 *
 */
export const packSourceCodeUploadComplete = <ThrowOnError extends boolean = false>(
  options: Options<PackSourceCodeUploadCompleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PackSourceCodeUploadCompleteResponse2,
    PackSourceCodeUploadCompleteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/versions/{packVersion}/sourceCode/uploadComplete",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * get the source code for a Pack version.
 * Get temporary links used to download the source code for the given packId and version
 *
 */
export const getPackSourceCode = <ThrowOnError extends boolean = false>(
  options: Options<GetPackSourceCodeData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetPackSourceCodeResponse, GetPackSourceCodeError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/versions/{packVersion}/sourceCode",
    ...options,
  });
};

/**
 * List the Pack listings accessible to a user.
 * Get listings of public Packs and Packs created by you.
 *
 */
export const listPackListings = <ThrowOnError extends boolean = false>(
  options?: Options<ListPackListingsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<ListPackListingsResponse, ListPackListingsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    querySerializer: {
      array: {
        explode: false,
        style: "form",
      },
    },
    url: "/packs/listings",
    ...options,
  });
};

/**
 * Get detailed listing information for a Pack.
 * Get detailed listing information for a Pack.
 *
 */
export const getPackListing = <ThrowOnError extends boolean = false>(
  options: Options<GetPackListingData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetPackListingResponse, GetPackListingError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/listing",
    ...options,
  });
};

/**
 * Retrieve the logs of a Pack.
 * Retrieve the logs of a Pack for debugging purpose.
 *
 */
export const listPackLogs = <ThrowOnError extends boolean = false>(
  options: Options<ListPackLogsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<ListPackLogsResponse, ListPackLogsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    querySerializer: {
      array: {
        explode: false,
        style: "form",
      },
    },
    url: "/packs/{packId}/docs/{docId}/logs",
    ...options,
  });
};

/**
 * Retrieve the logs of a Ingestion.
 * Retrieve the logs of a Ingestion for debugging purpose.
 */
export const listIngestionLogs = <ThrowOnError extends boolean = false>(
  options: Options<ListIngestionLogsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<ListIngestionLogsResponse, ListIngestionLogsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    querySerializer: {
      array: {
        explode: false,
        style: "form",
      },
    },
    url: "/packs/{packId}/organizationId/{organizationId}/rootIngestionId/{rootIngestionId}/logs",
    ...options,
  });
};

/**
 * Retrieve the grouped logs of a Pack.
 * Retrieve the grouped logs of a Pack for debugging purpose.
 *
 */
export const listGroupedPackLogs = <ThrowOnError extends boolean = false>(
  options: Options<ListGroupedPackLogsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<ListGroupedPackLogsResponse, ListGroupedPackLogsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/docs/{docId}/groupedLogs",
    ...options,
  });
};

/**
 * Retrieve the grouped logs of a Pack for a specific ingestionExecutionId.
 * Retrieve the grouped logs of a Pack for debugging purpose.
 *
 */
export const listGroupedIngestionLogs = <ThrowOnError extends boolean = false>(
  options: Options<ListGroupedIngestionLogsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListGroupedIngestionLogsResponse,
    ListGroupedIngestionLogsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/organizationId/{organizationId}/rootIngestionId/{rootIngestionId}/groupedLogs",
    ...options,
  });
};

/**
 * Retrieve a list of ingestion execution ids for the given root ingestion id.
 * Retrieve the ingestion execution ids of a root ingestion for debugging purpose.
 *
 */
export const listIngestionExecutions = <ThrowOnError extends boolean = false>(
  options: Options<ListIngestionExecutionsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListIngestionExecutionsResponse,
    ListIngestionExecutionsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/organizationId/{organizationId}/rootIngestionId/{rootIngestionId}/ingestionExecutions",
    ...options,
  });
};

/**
 * Retrieve a list of ingestion execution ids for the given root ingestion id.
 * Retrieve the ingestion execution ids of a root ingestion for debugging purpose.
 *
 */
export const listIngestionExecutionAttempts = <ThrowOnError extends boolean = false>(
  options: Options<ListIngestionExecutionAttemptsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListIngestionExecutionAttemptsResponse,
    ListIngestionExecutionAttemptsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/organizationId/{organizationId}/rootIngestionId/{rootIngestionId}/ingestionExecutionId/{ingestionExecutionId}/attempts",
    ...options,
  });
};

/**
 * Retrieve the information for a specific log.
 * Retrieve the ingestion execution ids of a root ingestion for debugging purpose.
 *
 */
export const getPackLogDetails = <ThrowOnError extends boolean = false>(
  options: Options<GetPackLogDetailsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetPackLogDetailsResponse, GetPackLogDetailsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/organizationId/{organizationId}/rootIngestionId/{rootIngestionId}/logs/{logId}",
    ...options,
  });
};

/**
 * List featured docs for a Pack
 * Returns a list of featured doc ids for a Pack.
 *
 */
export const listPackFeaturedDocs = <ThrowOnError extends boolean = false>(
  options: Options<ListPackFeaturedDocsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<ListPackFeaturedDocsResponse, ListPackFeaturedDocsError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/featuredDocs",
    ...options,
  });
};

/**
 * Update featured docs for a Pack
 * Create or replace the featured docs for a Pack.
 *
 */
export const updatePackFeaturedDocs = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePackFeaturedDocsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    UpdatePackFeaturedDocsResponse2,
    UpdatePackFeaturedDocsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/packs/{packId}/featuredDocs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Add a go link
 * Adds a new go link for the organization.
 */
export const addGoLink = <ThrowOnError extends boolean = false>(options: Options<AddGoLinkData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<AddGoLinkResponse, AddGoLinkError, ThrowOnError>({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/organizations/{organizationId}/goLinks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};
